name: Main Flow

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            auto-optimise-store = true
            keep-outputs = true
            keep-derivations = true
      - name: Cache nix
        uses: cachix/cachix-action@v12
        with:
          name: effect-ts
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Setup direnv
        uses: HatsuneMiku3939/direnv-action@v1
        with:
          direnvVersion: 2.32.2
      - run: bun install
      - run: bun run build
      - run: bun run circular
      - run: bun test --coverage
      - run: bun run lint
      - run: bun run dtslint
      - run: bun run docs
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: bun run version
          publish: bun exec changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
